In [59]:
#!pip install ipykernel

In [60]:
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

In [61]:
df=pd.read_json("News_Category_Dataset_v3.json", lines=True)

In [62]:
df.head()

,link,headline,category,short_description,authors,date
0,https://www.huffpost.com/entry/covid-boosters-...,Over 4 Million Americans Roll Up Sleeves For O...,U.S. NEWS,Health experts said it is too early to predict...,"Carla K. Johnson, AP",2022-09-23
1,https://www.huffpost.com/entry/american-airlin...,"American Airlines Flyer Charged, Banned For Li...",U.S. NEWS,He was subdued by passengers and crew when he ...,Mary Papenfuss,2022-09-23
2,https://www.huffpost.com/entry/funniest-tweets...,23 Of The Funniest Tweets About Cats And Dogs ...,COMEDY,"""Until you have a dog you don't understand wha...",Elyse Wanshel,2022-09-23
3,https://www.huffpost.com/entry/funniest-parent...,The Funniest Tweets From Parents This Week (Se...,PARENTING,"""Accidentally put grown-up toothpaste on my to...",Caroline Bologna,2022-09-23
4,https://www.huffpost.com/entry/amy-cooper-lose...,Woman Who Called Cops On Black Bird-Watcher Lo...,U.S. NEWS,Amy Cooper accused investment firm Franklin Te...,Nina Golgowski,2022-09-22


# Data Exploration

In [63]:
df.shape

(209527, 6)

In [64]:
df.columns

Index(['link', 'headline', 'category', 'short_description', 'authors', 'date'], dtype='str')

In [65]:
data=df['short_description'].sample(20000).reset_index(drop=True)

In [66]:
data

0        Anyone that has ever had kids knows toddlers c...
1        "It was the longest and scariest minute of my ...
2                                                         
3        Bess Kalb has names and dollar amounts for NRA...
4        “Oxytocin appears to be part of the way our bo...
                               ...                        
19995    Paramour Kanye West was nowhere in site as Kim...
19996    Last month was not the first time that former ...
19997    “This decision is perverse. It is illogical,” ...
19998    Most adolescents understand intellectually tha...
19999    From Assignment Fashion: This is definitely on...
Name: short_description, Length: 20000, dtype: str

In [67]:
data.shape

(20000,)

In [68]:
data[0]

'Anyone that has ever had kids knows toddlers can be completely unreasonable and absolutely impossible. The sayings “terrible'

In [69]:
data.isnull().sum()

np.int64(0)

In [70]:
data.duplicated().sum()

np.int64(1948)

In [71]:
data.drop_duplicates(inplace=True)

In [72]:
data.duplicated().sum()

np.int64(0)

In [73]:
data.shape

(18052,)

In [74]:
tokenizer=Tokenizer(oov_token='oov')

In [75]:
tokenizer.fit_on_texts(data)

In [76]:
tokenizer.word_index

{'oov': 1,
 'the': 2,
 'to': 3,
 'a': 4,
 'and': 5,
 'of': 6,
 'in': 7,
 'is': 8,
 'that': 9,
 'for': 10,
 'you': 11,
 'on': 12,
 'i': 13,
 'it': 14,
 'are': 15,
 'with': 16,
 'we': 17,
 'be': 18,
 'this': 19,
 'as': 20,
 'have': 21,
 'was': 22,
 'but': 23,
 'your': 24,
 'not': 25,
 'at': 26,
 'from': 27,
 'my': 28,
 'or': 29,
 'an': 30,
 'has': 31,
 'about': 32,
 'more': 33,
 'our': 34,
 'by': 35,
 'all': 36,
 'when': 37,
 'can': 38,
 'what': 39,
 'one': 40,
 'their': 41,
 'out': 42,
 'his': 43,
 'will': 44,
 'if': 45,
 'they': 46,
 'new': 47,
 'he': 48,
 'who': 49,
 "it's": 50,
 'time': 51,
 'people': 52,
 'her': 53,
 'up': 54,
 'so': 55,
 'just': 56,
 'like': 57,
 'do': 58,
 'how': 59,
 'some': 60,
 'been': 61,
 'said': 62,
 'than': 63,
 'there': 64,
 'no': 65,
 'us': 66,
 'most': 67,
 'year': 68,
 'me': 69,
 'get': 70,
 'had': 71,
 'after': 72,
 'day': 73,
 'she': 74,
 'first': 75,
 'would': 76,
 'into': 77,
 'were': 78,
 'these': 79,
 'make': 80,
 'life': 81,
 'over': 82,
 'want':

In [77]:
len(tokenizer.word_index)

29353

In [78]:
data=tokenizer.texts_to_sequences(data)

In [79]:
data

[[520,
  9,
  31,
  163,
  71,
  173,
  854,
  7136,
  38,
  18,
  837,
  10748,
  5,
  1107,
  1962,
  2,
  15055,
  15056],
 [14, 22, 2, 4081, 5, 10749, 995, 6, 28, 81],
 [],
 [15057, 15058, 31, 1360, 5, 1963, 3106, 10, 4909, 2049, 1269],
 [15059, 1415, 3, 18, 184, 6, 2, 93, 34, 1755, 315, 1633, 3526],
 [90, 584, 347, 56, 57, 66, 1884, 25],
 [2, 6186, 8, 245, 1820],
 [2,
  164,
  151,
  10750,
  8525,
  10751,
  15060,
  65,
  473,
  37,
  416,
  32,
  43,
  5485,
  12,
  432,
  1160,
  7137,
  10751],
 [17,
  36,
  21,
  4910,
  10,
  25,
  646,
  336,
  702,
  28,
  7138,
  4910,
  15,
  2124,
  14,
  3527,
  330,
  516,
  128,
  160,
  3,
  80,
  8,
  15061,
  5,
  326,
  2,
  3795,
  2659,
  3,
  4453,
  163,
  45,
  11,
  91,
  10752,
  14,
  129,
  256,
  23,
  168,
  13,
  1161,
  9,
  67,
  1304,
  15062,
  21,
  2,
  7139,
  1228,
  6,
  4,
  15063],
 [1190, 3528, 7, 1020, 8526, 1885, 82, 1886, 15064, 3292, 5, 2660],
 [64,
  15,
  4,
  167,
  142,
  19,
  239,
  1756,
  69,


In [80]:
input_sequence=[]
for sequence in data:
    if len(sequence)<2:
        continue
    for i in range(1, len(sequence)):
        ngram=sequence[:i+1]
        input_sequence.append(ngram)

In [81]:
input_sequence

[[520, 9],
 [520, 9, 31],
 [520, 9, 31, 163],
 [520, 9, 31, 163, 71],
 [520, 9, 31, 163, 71, 173],
 [520, 9, 31, 163, 71, 173, 854],
 [520, 9, 31, 163, 71, 173, 854, 7136],
 [520, 9, 31, 163, 71, 173, 854, 7136, 38],
 [520, 9, 31, 163, 71, 173, 854, 7136, 38, 18],
 [520, 9, 31, 163, 71, 173, 854, 7136, 38, 18, 837],
 [520, 9, 31, 163, 71, 173, 854, 7136, 38, 18, 837, 10748],
 [520, 9, 31, 163, 71, 173, 854, 7136, 38, 18, 837, 10748, 5],
 [520, 9, 31, 163, 71, 173, 854, 7136, 38, 18, 837, 10748, 5, 1107],
 [520, 9, 31, 163, 71, 173, 854, 7136, 38, 18, 837, 10748, 5, 1107, 1962],
 [520, 9, 31, 163, 71, 173, 854, 7136, 38, 18, 837, 10748, 5, 1107, 1962, 2],
 [520,
  9,
  31,
  163,
  71,
  173,
  854,
  7136,
  38,
  18,
  837,
  10748,
  5,
  1107,
  1962,
  2,
  15055],
 [520,
  9,
  31,
  163,
  71,
  173,
  854,
  7136,
  38,
  18,
  837,
  10748,
  5,
  1107,
  1962,
  2,
  15055,
  15056],
 [14, 22],
 [14, 22, 2],
 [14, 22, 2, 4081],
 [14, 22, 2, 4081, 5],
 [14, 22, 2, 4081, 5, 1074

In [82]:
max_length=max([len(i) for i in input_sequence])

In [83]:
max_length

170

In [84]:
input=pad_sequences(input_sequence, padding='pre', maxlen=max_length)

In [85]:
input

array([[  0,   0,   0, ...,   0, 520,   9],
       [  0,   0,   0, ..., 520,   9,  31],
       [  0,   0,   0, ...,   9,  31, 163],
       ...,
       [  0,   0,   0, ...,  12,   2, 930],
       [  0,   0,   0, ...,   2, 930, 129],
       [  0,   0,   0, ..., 930, 129,  88]],
      shape=(377114, 170), dtype=int32)

In [86]:
X=input[:,:-1]
y=input[:,-1]

In [87]:
X

array([[    0,     0,     0, ...,     0,     0,   520],
       [    0,     0,     0, ...,     0,   520,     9],
       [    0,     0,     0, ...,   520,     9,    31],
       ...,
       [    0,     0,     0, ..., 10716,    12,     2],
       [    0,     0,     0, ...,    12,     2,   930],
       [    0,     0,     0, ...,     2,   930,   129]],
      shape=(377114, 169), dtype=int32)

In [88]:
y=np.array(y)

In [89]:
y

array([  9,  31, 163, ..., 930, 129,  88], shape=(377114,), dtype=int32)

In [90]:
X.shape, y.shape

((377114, 169), (377114,))

In [91]:
from sklearn.model_selection import train_test_split

In [92]:
X_train, X_test, y_train, y_test= train_test_split(X,y, test_size=0.2, random_state=42)

In [93]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((301691, 169), (75423, 169), (301691,), (75423,))

In [94]:
vocab_size=len(tokenizer.word_index)+1

In [95]:
vocab_size

29354

In [96]:
max_len=X.shape[1]+1

In [97]:
max_len

170

In [98]:
model=Sequential(
    [Embedding(vocab_size, 128, input_length=max_len),
     LSTM(256),
     Dense(vocab_size, activation='softmax')]
)

e:\ZZZZ-Complete_GenAI\Tutudude_class\LSTM\venv\Lib\site-packages\keras\src\layers\core\embedding.py:103: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [99]:
model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

In [100]:
model.build(input_shape=(None, max_len))

In [102]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 170, 128)       │     3,757,312 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ (None, 256)            │       394,240 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 29354)          │     7,543,978 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 11,695,530 (44.61 MB)

 Trainable params: 11,695,530 (44.61 MB)

 Non-trainable params: 0 (0.00 B)

In [103]:
model.fit(X_train, y_train, epochs=10, validation_data=(X_test, y_test), batch_size=32)

Epoch 1/10
2135/9428 ━━━━━━━━━━━━━━━━━━━━ 3:42:37 2s/step - accuracy: 0.0487 - loss: 7.9412

KeyboardInterrupt: 

In [ ]:
model.save('nextword_model.h5')

In [ ]:
import pickle
with open('tokenizer.pkl','wb') as file:
    pickle.dump(tokenizer, file)